### PR TITLE
Critical points

### PR DESCRIPTION
**Pull request by jrleeman**
Automatically determines critical times for integrated based upon the acceleration of the load-point. Will handle uneven time spacing.

### CODE REVIEW

**Comment by jrleeman** [comment]
Not sure why Travis is failing. All tests run fine for me locally.

**Comment by dopplershift** [comment]
Run fine on my mac and on an ubuntu 15.04 64-bit vm. Might want to test against Ubuntu 12.04 64-bit, which is what Travis runs. Have you ever used virtual box?

**Comment by jrleeman** [comment]
I use parallels. I made a 12.04 machine and followed the way Travis does things and all tests pass... Hmmm

**Comment by jrleeman** [comment]
Since this is failing on a clean build 12.04 machine, should be contact the folks at Travis? I've played with it some and can't find any knobs to turn to fix this.

**Comment by dopplershift** [comment]
On a whim, can you try adding this to the `.travis.yml`:
```yml
addons:
  apt:
    packages:
    - libblas3gf
    - liblapack3gf
```
This is telling it explicitly to install blas/lapack.

**Comment by jrleeman** [comment]
Just did (you can see results on Travis page). No dice.

**Comment by dopplershift** [comment]
Hmmmm. What about:
```yml
sudo: required
```

This will run on a VM rather than a Docker container. Just trying to reduce differences (really changing this should make no difference at all) between what you have working locally and what fails on Travis.

Your best bet contacting them would be to ask for for something specific you could use to debug, like a list of the packages they install. I guess another option is to add the command to list all installed packages from apt-get to `.travis.yml`. That would allow you to better replicate the Travis environment locally, hopefully reproducing the problem.

**Comment by jrleeman** [comment]
That didn't help unfortunately. Just commenting out the tcrit part made everything happy again, so at least we know what is causing the issue. I'll see if there are some maxstep params to tweak.

**Comment by jrleeman** [comment]
Ok. If I increase the mxstep argument, everything runs fine. It's strange that it is necessary for Travis, but not on our systems. The problem with the way I did it above is that we can't let the user set mxstep when calling solve:

```Python
model.solve(mxstep=5000)
```

We get a multiple values for keyword argument error.

**Comment by dopplershift** [comment]
Add `mxstep` to `odeint_kwargs` if it's not there. You could also even check that if the user passes it in, the value is in the right range and could warn if not.

**Comment by jrleeman** [comment]
Okay, I decided to leave the checking out currently. Is most cases a low mxsteps is fine, but for very stiff cases more steps are needed. 5000 (the default I set) should be enough for just about anything. Finally passes build and tests.

**Pull request merged**
